### ISSUE TITLE
pip install does not seem to work 

### ISSUE THREAD

**Issue by GiuseppeCiccone96** [hanjinliu/tabulous#14]
Hello, 

I have created a conda env to play with tabulous  (conda create -n tabs) and used pip install tabulous[all] in that env; when I run the following code 

```python 
from tabulous import TableViewer
viewer = TableViewer()
```
I get the following: 

```python
 File "tab.py", line 1, in <module>
    from tabulous import TableViewer
ImportError: No module named tabulous
```

Any idea why? 

Giuseppe

**Comment by hanjinliu** [comment]
Hi @GiuseppeCiccone96 ,
I created new environment and tested the installation but it worked well. How are you running the tab.py code? If you are running it from an editor, you may want to check the python path setting first. To check if installation itself was succesfully done, the mose reliable way is to launch Python REPL. 
```
$ python
>>> import tabulous
```

**Comment by GiuseppeCiccone96** [comment]
Hi @hanjinliu , I managed - not sure what was going wrong!
